=== blacktop/symbolicator/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://github.com/blacktop/ipsw/pkg/signature/symbolicator",
	"$ref": "#/$defs/Symbolicator",
	"$defs": {
		"Anchor": {
			"properties": {
				"string": {
					"type": "string"
				},
				"segment": {
					"type": "string"
				},
				"section": {
					"type": "string"
				},
				"caller": {
					"oneOf": [
						{
							"type": "string"
						},
						{
							"type": "null"
						}
					]
				}
			},
			"additionalProperties": false,
			"type": "object",
			"required": [
				"string",
				"segment",
				"section"
			]
		},
		"Signature": {
			"properties": {
				"args": {
					"type": "integer"
				},
				"anchors": {
					"items": {
						"$ref": "#/$defs/Anchor"
					},
					"type": "array"
				},
				"symbol": {
					"type": "string"
				},
				"prototype": {
					"type": "string"
				},
				"backtrace": {
					"items": {
						"type": "string"
					},
					"type": "array"
				},
				"provenance": {
					"description": "Confidence source for the symbol; defaults to \"direct\" when absent.",
					"type": "string",
					"enum": [
						"direct",
						"dual-evidence",
						"propagated",
						"weak-string+callee"
					]
				}
			},
			"additionalProperties": false,
			"type": "object",
			"required": [
				"args",
				"anchors",
				"symbol",
				"prototype"
			]
		},
		"Symbolicator": {
			"properties": {
				"target": {
					"type": "string"
				},
				"total": {
					"type": "integer"
				},
				"version": {
					"$ref": "#/$defs/Version"
				},
				"signatures": {
					"items": {
						"$ref": "#/$defs/Signature"
					},
					"type": "array"
				}
			},
			"additionalProperties": false,
			"type": "object",
			"required": [
				"target",
				"total",
				"version",
				"signatures"
			]
		},
		"Version": {
			"properties": {
				"max": {
					"type": "string"
				},
				"min": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"type": "object",
			"required": [
				"max",
				"min"
			]
		}
	},
	"description": "ipsw Symbolicator definition file"
}

=== blacktop/symbolicator/kernel/25.6/kexts/AppleVmxnet3Ethernet.json
{
    "target": "com.apple.driver.AppleVmxnet3Ethernet",
    "total": 13,
    "version": {
        "max": "25.7.0",
        "min": "25.6.0"
    },
    "signatures": [
        {
            "args": 1,
            "anchors": [
                {
                    "string": "local-mac-address",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController5probeEP9IOServicePi",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "IONetworkStatsKey",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_ifnet_set_tso_mtu"
                },
                {
                    "string": "IOEthernetStatsKey",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZNK18IONetworkInterface12getParameterEPKc"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController5startEP9IOService",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "IOInterfaceUnit",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_printf"
                },
                {
                    "string": "WARNING: using bogus hardcoded station address\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_printf"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController18vmxnet3_get_lladdrEv",
            "prototype": "",
            "backtrace": [
                "__ZN21AppleVMXNETController5startEP9IOService"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "hw.activecpu",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_sysctlbyname"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController17alloc_shared_dataEv",
            "prototype": "",
            "backtrace": [
                "__ZN21AppleVMXNETController5startEP9IOService"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "Header alignment failed.!!!\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_kprintf"
                },
                {
                    "string": "\nACK: genPhysicalSegments returned %d\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_kprintf"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController14setup_rx_queueEi",
            "prototype": "",
            "backtrace": [
                "__ZN21AppleVMXNETController15alloc_rx_queuesEv",
                "__ZN21AppleVMXNETController5startEP9IOService"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "Failed to set polling paramters.!!!\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_printf"
                }
            ],
            "symbol": "__ZN21AppleVMXNETController19vmxnet3_link_statusEv",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 1,
            "anchors": [],
            "symbol": "__ZN21AppleVMXNETController15alloc_rx_queuesEv",
            "prototype": "",
            "backtrace": [
                "__ZN21AppleVMXNETController14setup_rx_queueEi"
            ],
            "provenance": "propagated"
        }
    ]
}

=== blacktop/symbolicator/kernel/25.3/kexts/CryptoEncoding.json
{
    "target": "com.apple.driver.DiskImages.CryptoEncoding",
    "total": 6,
    "version": {
        "max": "25.4.0",
        "min": "25.3.0"
    },
    "signatures": [
        {
            "args": 0,
            "anchors": [
                {
                    "string": "hmacsha1-key",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN6KDIURL9getSecretEPKc"
                },
                {
                    "string": "encryption-key",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_SHA1Update"
                }
            ],
            "symbol": "__ZN20KDIEncryptedEncoding13_loadContextsEv",
            "prototype": "",
            "backtrace": [
                "__ZN20KDIEncryptedEncoding12_handleStartEP9IOService"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "KDIEncryptedEncoding: repairing file: backing store length %qd, expected %qd\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                },
                {
                    "string": "                    : REPAIR FAILED!\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                }
            ],
            "symbol": "__ZN20KDIEncryptedEncoding17_rationalizeSizesEv",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 1,
            "anchors": [],
            "symbol": "__ZN20KDIEncryptedEncoding12_handleStartEP9IOService",
            "prototype": "",
            "backtrace": [
                "__ZN20KDIEncryptedEncoding13_loadContextsEv"
            ],
            "provenance": "propagated"
        }
    ]
}

=== blacktop/symbolicator/kernel/27.2/kexts/AppleHollywood.json
{
    "target": "com.apple.driver.AppleHollywood",
    "total": 3,
    "version": {
        "max": "28.0.0",
        "min": "27.2.0"
    },
    "signatures": [
        {
            "args": 0,
            "anchors": [
                {
                    "string": "CD Features Mask",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                },
                {
                    "string": "DVD Features Mask",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                },
                {
                    "string": "CD Features",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN9OSBoolean11withBooleanEb"
                },
                {
                    "string": "DVD Features",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN9OSBoolean11withBooleanEb"
                },
                {
                    "string": "Low Power Polling",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                },
                {
                    "string": "CD-DA support",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                }
            ],
            "symbol": "__ZN31com_apple_driver_AppleHollywood23DetermineDeviceFeaturesEv",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        }
    ]
}

=== blacktop/symbolicator/kernel/27.0/kexts/AGXFirmwareKextG13GRTBuddy.json
{
    "target": "com.apple.AGXFirmwareKextG13GRTBuddy",
    "total": 18,
    "version": {
        "max": "28.0.0",
        "min": "27.0.0"
    },
    "signatures": [
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AGXFirmwareKextG13RTBuddy",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN8OSSymbol17withCStringNoCopyEPKc"
                }
            ],
            "symbol": "__GLOBAL__sub_I_agxp_kext_g13_rtbuddy.cpp",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AGXRTBuddyMessageWorkLoop",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_thread_set_thread_name"
                }
            ],
            "symbol": "__ZN22AGXFirmwareKextRTBuddy5startEP9IOService",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "coredump-copy-buffer",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
                }
            ],
            "symbol": "__ZNK22AGXFirmwareKextRTBuddy32getCoredumpCopyBufferEDTPropertyEv",
            "prototype": "",
            "backtrace": [
                "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AGXk: %s:%d:%s: !!! GFX firmware was not loaded by iBoot\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                },
                {
                    "string": "Endpoint1",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_strlcpy"
                },
                {
                    "string": "Endpoint2",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_strlcpy"
                }
            ],
            "symbol": "__ZN22AGXFirmwareKextRTBuddy12bootFirmwareEP11IOMemoryMap",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AGXk: %s:%d:%s: !!! Power state change to Sleep did not complete!\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                },
                {
                    "string": "AGXk: %s:%d:%s: !!! Scheduler work queues disabled but command submission is still enabled\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN22AGXFirmwareKextRTBuddy16powerStateChangeEmm",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AGXk: %s:%d:%s: !!! Error, trying to change power state with disabled fender power management!\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN22AGXFirmwareKextRTBuddy21powerStateChangeGatedEmm",
            "prototype": "",
            "backtrace": [
                "_panic"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [],
            "symbol": "_panic",
            "prototype": "",
            "backtrace": [
                "__ZN22AGXFirmwareKextRTBuddy21powerStateChangeGatedEmm"
            ],
            "provenance": "propagated"
        },
        {
            "args": 0,
            "anchors": [],
            "symbol": "__ZN15OSMetaClassBase12safeMetaCastEPKS_PK11OSMetaClass",
            "prototype": "",
            "backtrace": [
                "__ZNK22AGXFirmwareKextRTBuddy32getCoredumpCopyBufferEDTPropertyEv"
            ],
            "provenance": "propagated"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual const char *AGXFirmwareKextG13RTBuddy::getVersion(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy10getVersionE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual bool AGXFirmwareKextG13RTBuddy::requestFirmwareBinary(const uint8_t **, size_t *, const AGXGPUCoreConfig &, AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy21requestFirmwareBinaryEPPKhPmRK16AGXGPUCoreConfig16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual uint32_t AGXFirmwareKextG13RTBuddy::getBootConfigOffset(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy19getBootConfigOffsetE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual uint32_t AGXFirmwareKextG13RTBuddy::getFWResumeFlagOffset(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy21getFWResumeFlagOffsetE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual uint32_t AGXFirmwareKextG13RTBuddy::getFWPdumpBinPatchDataOffset(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy28getFWPdumpBinPatchDataOffsetE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual size_t AGXFirmwareKextG13RTBuddy::getRuntimeBinSize(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy17getRuntimeBinSizeE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "virtual const char *AGXFirmwareKextG13RTBuddy::getBuild(AGFIFirmwareRole)",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "__ZN25AGXFirmwareKextG13RTBuddy8getBuildE16AGFIFirmwareRole",
            "prototype": "",
            "backtrace": [],
            "provenance": "dual-evidence"
        }
    ]
}

=== blacktop/symbolicator/kernel/27.2/kexts/AppleUSBCommon.json
{
    "target": "com.apple.driver.usb.AppleUSBCommon",
    "total": 19,
    "version": {
        "max": "28.0.0",
        "min": "27.2.0"
    },
    "signatures": [
        {
            "args": 1,
            "anchors": [
                {
                    "string": "%s-debug",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_snprintf"
                },
                {
                    "string": "AppleUSBCommonDebug@%s-debug",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_snprintf"
                }
            ],
            "symbol": "__ZN19AppleUSBCommonDebug31getDebugLoggingMaskForMetaClassEPK11OSMetaClassS2_PKc",
            "prototype": "",
            "backtrace": [
                "__ZN19AppleUSBRequestPool16initWithWorkLoopEP10IOWorkLoop"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "com.apple.usb",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_os_log_create"
                },
                {
                    "string": "debug",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_os_log_create"
                },
                {
                    "string": "-restore",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_PE_parse_boot_argn"
                },
                {
                    "string": "AppleUSBCommon-debug",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_PE_parse_boot_argn"
                }
            ],
            "symbol": "__ZN27AppleUSBCommonDebugBootArgsC2Ev",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "%s: %s::%s: memory descriptor still set\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                }
            ],
            "symbol": "____ZN19AppleUSBRequestPool16returnDMACommandEP12IODMACommand_block_invoke",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AppleUSBRequest.cpp",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "____ZN19AppleUSBRequestPool16returnDMACommandEP12IODMACommand_block_invoke.cold.1",
            "prototype": "",
            "backtrace": [
                "_panic",
                "____ZN19AppleUSBRequestPool16returnDMACommandEP12IODMACommand_block_invoke"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "usb_bundling_timeout",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_PE_parse_boot_argn"
                }
            ],
            "symbol": "__ZN24AppleUSBRequestCompleter4initEP8OSObjectP10IOWorkLoopPFvS1_zE",
            "prototype": "",
            "backtrace": [
                "__ZN24AppleUSBRequestCompleter16requestCompleterEP8OSObjectP10IOWorkLoop"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "%s: %s::%s: queues not empty\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                },
                {
                    "string": "%s: %s::%s: queues not empty\n",
                    "segment": "__TEXT",
                    "section": "__os_log",
                    "caller": "__os_log_internal"
                }
            ],
            "symbol": "__ZN24AppleUSBRequestCompleter4freeEv",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "AppleUSBRequestCompleter.cpp",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_panic"
                }
            ],
            "symbol": "_OUTLINED_FUNCTION_0",
            "prototype": "",
            "backtrace": [
                "_panic"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "%s: %s::%s: thread_call failed with 0x%08x",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                },
                {
                    "string": "%s: %s::%s: request completer mismatch\n",
                    "segment": "__TEXT",
                    "section": "__os_log",
                    "caller": "__os_log_internal"
                },
                {
                    "string": "%s: %s::%s: thread_call failed with 0x%08x",
                    "segment": "__TEXT",
                    "section": "__os_log",
                    "caller": "__os_log_internal"
                }
            ],
            "symbol": "__ZN24AppleUSBRequestCompleter14enqueueRequestEP15AppleUSBRequest",
            "prototype": "",
            "backtrace": [
                "__ZN24AppleUSBRequestCompleter20completeRequestChainEP15AppleUSBRequest"
            ],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "%s: %s::%s: _queueSnapshot is not empty\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                },
                {
                    "string": "%s: %s::%s: _queueSnapshot is not empty\n",
                    "segment": "__TEXT",
                    "section": "__os_log",
                    "caller": "__os_log_internal"
                }
            ],
            "symbol": "__ZN24AppleUSBRequestCompleter12checkForWorkEv",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 0,
            "anchors": [
                {
                    "string": "%s: %s::%s: thread_call failed with 0x%08x\n",
                    "segment": "__TEXT",
                    "section": "__cstring",
                    "caller": "_IOLog"
                },
                {
                    "string": "%s: %s::%s: thread_call failed with 0x%08x\n",
                    "segment": "__TEXT",
                    "section": "__os_log",
                    "caller": "__os_log_internal"
                }
            ],
            "symbol": "__ZN24AppleUSBRequestCompleter20completeRequestQueueEP11queue_entry",
            "prototype": "",
            "backtrace": [],
            "provenance": "direct"
        },
        {
            "args": 1,
            "anchors": [],
            "symbol": "__ZN24AppleUSBRequestCompleter20completeRequestChainEP15AppleUSBRequest",
            "prototype": "",
            "backtrace": [
                "__ZN24AppleUSBRequestCompleter14enqueueRequestEP15AppleUSBRequest"
            ],
            "provenance": "propagated"
        },
        {
            "args": 0,
            "anchors": [],
            "symbol": "_panic",
            "prototype": "",
            "backtrace": [
                "____ZN19AppleUSBRequestPool16returnDMACommandEP12IODMACommand_block_invoke.cold.1"
            ],
            "provenance": "propagated"
        },
        {
            "args": 0,
            "anchors": [],
            "symbol": "__ZN19AppleUSBRequestPool16initWithWorkLoopEP10IOWorkLoop",
            "prototype": "",
            "backtrace": [
                "__ZN19AppleUSBCommonDebug31getDebugLoggingMaskForMetaClassEPK11OSMetaClassS2_PKc"
            ],
            "provenance": "propagated"
        },
        {
            "args": 0,
            "anchors": [],
            "symbol": "__ZN24AppleUSBRequestCompleter16requestCompleterEP8OSObjectP10IOWorkLoop",
            "prototype": "",
            "backtrace": [
                "__ZN24AppleUSBRequestCompleter4initEP8OSObjectP10IOWorkLoopPFvS1_zE"
            ],
            "provenance": "propagated"
        }
    ]
}
